# Generated by Django 4.1.13 on 2024-11-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_note_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='font_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='note',
            name='font_style',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
